name: Release version 1.x.x. fix

description: |
  Organizes CI/CD pipeline for branch with fixes for major version 1.x.x (version-1.x.x/fixes) - generate Changelog and bump version automatically,
  create a release PR which once merged results in creating a new GitHub release and publishing a new version of NPM
  package

on:
  push:
    branches: [version-1.x.x/fixes]

inputs:
  github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
  npm-token: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
  node-version: 14

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        shell: bash
      - run: npm test
        shell: bash
      - uses: codex-team/action-nodejs-package-info@v1
        id: package
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ inputs.github-token }}
          release-type: node
          package-name: ${{ steps.package.outputs.name }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false}]'
          bump-minor-pre-major: true
          default-branch: ${{ inputs.default-branch }}
      - run: npm publish --tag untagged --access public
        env:
          NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
